=== Tubbz-alt/epb-register-api/api/schemas/xml/CEPC-7.1/Messages/ExternalDefinitions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 rel. 3 U (http://www.altova.com) by Jim Bowery (Landmark Information Group Ltd.) -->
<xs:schema xmlns="EPC" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="EPC" attributeFormDefault="unqualified">
	<xs:annotation>
		<xs:documentation>
			This schema is used to provide 
				(a) the options for Related Party Disclosure
		</xs:documentation>
	</xs:annotation>
	<xs:element name="ExternalDefinitions" type="ExternalDefinitions"/>
	<xs:complexType name="ExternalDefinitions">
		<xs:sequence>
			<xs:element name="Revision-Number" type="xs:string">
				<xs:annotation>
					<xs:documentation>The version number of the latest revision to any of the texts</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Revision-Date" type="xs:date">
				<xs:annotation>
					<xs:documentation>The date of the latest revision to any of the texts</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="DEC-Related-Party-Disclosure" type="DEC-Related-Party-Disclosure" maxOccurs="unbounded"/>
			<xs:element name="EPC-Related-Party-Disclosure" type="EPC-Related-Party-Disclosure" maxOccurs="unbounded"/>
			<xs:element name="ACI-Related-Party-Disclosure" type="ACI-Related-Party-Disclosure" maxOccurs="unbounded"/>
			<xs:element name="Refrigerant-Type" type="Refrigerant-Type" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DEC-Related-Party-Disclosure">
		<xs:annotation>
			<xs:documentation>List of possible texts for Related Party Disclosure on DECs</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="DEC-Disclosure-Code" type="xs:positiveInteger"/>
			<xs:element name="DEC-Disclosure-Text" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="EPC-Related-Party-Disclosure">
		<xs:annotation>
			<xs:documentation>List of possible texts for Related Party Disclosure on EPCs</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="EPC-Disclosure-Code" type="xs:positiveInteger"/>
			<xs:element name="EPC-Disclosure-Text" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ACI-Related-Party-Disclosure">
		<xs:annotation>
			<xs:documentation>List of possible texts for Related Party Disclosure on ACIs</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="ACI-Disclosure-Code" type="xs:positiveInteger"/>
			<xs:element name="ACI-Disclosure-Text" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Refrigerant-Type">
		<xs:sequence>
			<xs:element name="Type" type="xs:string"/>
			<xs:element name="ECFGasRegulation" type="RefrigerantRegulationFlag"/>
			<xs:element name="ECOzoneRegulation" type="RefrigerantRegulationFlag"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="RefrigerantRegulationFlag">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Relevant and must comply"/>
			<xs:enumeration value="Not relevant"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== Tubbz-alt/epb-register-api/api/schemas/xml/NI-CEPC-7.1/Messages/ExternalDefinitions.xml
<?xml version="1.0" encoding="UTF-8"?>
<n1:ExternalDefinitions xmlns:n1="EPC" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="EPC
.\ExternalDefinitions.xsd">
	<Revision-Number>3.1</Revision-Number>
	<Revision-Date>2011-05-11</Revision-Date>
	<DEC-Related-Party-Disclosure>
		<DEC-Disclosure-Code>1</DEC-Disclosure-Code>
		<DEC-Disclosure-Text>Not related to the occupier.</DEC-Disclosure-Text>
	</DEC-Related-Party-Disclosure>
	<DEC-Related-Party-Disclosure>
		<DEC-Disclosure-Code>2</DEC-Disclosure-Code>
		<DEC-Disclosure-Text>Employed by the occupier.</DEC-Disclosure-Text>
	</DEC-Related-Party-Disclosure>
	<DEC-Related-Party-Disclosure>
		<DEC-Disclosure-Code>3</DEC-Disclosure-Code>
		<DEC-Disclosure-Text>Contractor to the occupier for EPBD services only.</DEC-Disclosure-Text>
	</DEC-Related-Party-Disclosure>
	<DEC-Related-Party-Disclosure>
		<DEC-Disclosure-Code>4</DEC-Disclosure-Code>
		<DEC-Disclosure-Text>Contractor to the occupier for non-EPBD services.</DEC-Disclosure-Text>
	</DEC-Related-Party-Disclosure>
	<DEC-Related-Party-Disclosure>
		<DEC-Disclosure-Code>5</DEC-Disclosure-Code>
		<DEC-Disclosure-Text>Indirect relation to the occupier.</DEC-Disclosure-Text>
	</DEC-Related-Party-Disclosure>
	<DEC-Related-Party-Disclosure>
		<DEC-Disclosure-Code>6</DEC-Disclosure-Code>
		<DEC-Disclosure-Text>Financial interest in the occupier and/or property.</DEC-Disclosure-Text>
	</DEC-Related-Party-Disclosure>
	<DEC-Related-Party-Disclosure>
		<DEC-Disclosure-Code>7</DEC-Disclosure-Code>
		<DEC-Disclosure-Text>Previous relation to the occupier.</DEC-Disclosure-Text>
	</DEC-Related-Party-Disclosure>
	<DEC-Related-Party-Disclosure>
		<DEC-Disclosure-Code>8</DEC-Disclosure-Code>
		<DEC-Disclosure-Text>Not recorded.</DEC-Disclosure-Text>
	</DEC-Related-Party-Disclosure>
	<EPC-Related-Party-Disclosure>
		<EPC-Disclosure-Code>1</EPC-Disclosure-Code>
		<EPC-Disclosure-Text>Not related to the owner.</EPC-Disclosure-Text>
	</EPC-Related-Party-Disclosure>
	<EPC-Related-Party-Disclosure>
		<EPC-Disclosure-Code>2</EPC-Disclosure-Code>
		<EPC-Disclosure-Text>Relative of the owner.</EPC-Disclosure-Text>
	</EPC-Related-Party-Disclosure>
	<EPC-Related-Party-Disclosure>
		<EPC-Disclosure-Code>3</EPC-Disclosure-Code>
		<EPC-Disclosure-Text>Relative of the professional dealing with the property transaction.</EPC-Disclosure-Text>
	</EPC-Related-Party-Disclosure>
	<EPC-Related-Party-Disclosure>
		<EPC-Disclosure-Code>4</EPC-Disclosure-Code>
		<EPC-Disclosure-Text>Indirect relation to the owner (e.g relative employed/contracted by owner).</EPC-Disclosure-Text>
	</EPC-Related-Party-Disclosure>
	<EPC-Related-Party-Disclosure>
		<EPC-Disclosure-Code>5</EPC-Disclosure-Code>
		<EPC-Disclosure-Text>Occupier of the property.</EPC-Disclosure-Text>
	</EPC-Related-Party-Disclosure>
	<EPC-Related-Party-Disclosure>
		<EPC-Disclosure-Code>6</EPC-Disclosure-Code>
		<EPC-Disclosure-Text>Owner or Director of the organisation dealing with the property transaction.</EPC-Disclosure-Text>
	</EPC-Related-Party-Disclosure>
	<EPC-Related-Party-Disclosure>
		<EPC-Disclosure-Code>7</EPC-Disclosure-Code>
		<EPC-Disclosure-Text>Employed by the organisation dealing with the property transaction.</EPC-Disclosure-Text>
	</EPC-Related-Party-Disclosure>
	<EPC-Related-Party-Disclosure>
		<EPC-Disclosure-Code>8</EPC-Disclosure-Code>
		<EPC-Disclosure-Text>Financial interest in the property.</EPC-Disclosure-Text>
	</EPC-Related-Party-Disclosure>
	<EPC-Related-Party-Disclosure>
		<EPC-Disclosure-Code>9</EPC-Disclosure-Code>
		<EPC-Disclosure-Text>Employed by the owner.</EPC-Disclosure-Text>
	</EPC-Related-Party-Disclosure>
	<EPC-Related-Party-Disclosure>
		<EPC-Disclosure-Code>10</EPC-Disclosure-Code>
		<EPC-Disclosure-Text>Contracted by the owner to provide other Energy Assessment services.</EPC-Disclosure-Text>
	</EPC-Related-Party-Disclosure>
	<EPC-Related-Party-Disclosure>
		<EPC-Disclosure-Code>11</EPC-Disclosure-Code>
		<EPC-Disclosure-Text>Contracted by the owner to provide other (non Energy Assessment) services.</EPC-Disclosure-Text>
	</EPC-Related-Party-Disclosure>
	<EPC-Related-Party-Disclosure>
		<EPC-Disclosure-Code>12</EPC-Disclosure-Code>
		<EPC-Disclosure-Text>Previous relation to the owner (e.g. employee/contractor).</EPC-Disclosure-Text>
	</EPC-Related-Party-Disclosure>
	<EPC-Related-Party-Disclosure>
		<EPC-Disclosure-Code>13</EPC-Disclosure-Code>
		<EPC-Disclosure-Text>Not recorded.</EPC-Disclosure-Text>
	</EPC-Related-Party-Disclosure>
	<ACI-Related-Party-Disclosure>
		<ACI-Disclosure-Code>1</ACI-Disclosure-Code>
		<ACI-Disclosure-Text>Not related to the owner/occupier or person who has technical control of the system or subcontractor.</ACI-Disclosure-Text>
	</ACI-Related-Party-Disclosure>
	<ACI-Related-Party-Disclosure>
		<ACI-Disclosure-Code>2</ACI-Disclosure-Code>
		<ACI-Disclosure-Text>Related to the building owner/occupier.</ACI-Disclosure-Text>
	</ACI-Related-Party-Disclosure>
	<ACI-Related-Party-Disclosure>
		<ACI-Disclosure-Code>3</ACI-Disclosure-Code>
		<ACI-Disclosure-Text>Related to the person who has technical control of the system or subcontractor.</ACI-Disclosure-Text>
	</ACI-Related-Party-Disclosure>
	<ACI-Related-Party-Disclosure>
		<ACI-Disclosure-Code>4</ACI-Disclosure-Code>
		<ACI-Disclosure-Text>Occupier of the building.</ACI-Disclosure-Text>
	</ACI-Related-Party-Disclosure>
	<ACI-Related-Party-Disclosure>
		<ACI-Disclosure-Code>5</ACI-Disclosure-Code>
		<ACI-Disclosure-Text>Owner or Director of the organisation.</ACI-Disclosure-Text>
	</ACI-Related-Party-Disclosure>
	<ACI-Related-Party-Disclosure>
		<ACI-Disclosure-Code>6</ACI-Disclosure-Code>
		<ACI-Disclosure-Text>Financial interest in the building/organisation with technical control of the system or subcontractor.</ACI-Disclosure-Text>
	</ACI-Related-Party-Disclosure>
	<ACI-Related-Party-Disclosure>
		<ACI-Disclosure-Code>7</ACI-Disclosure-Code>
		<ACI-Disclosure-Text>Contracted by the owner to provide other Energy Assessment services.</ACI-Disclosure-Text>
	</ACI-Related-Party-Disclosure>
	<ACI-Related-Party-Disclosure>
		<ACI-Disclosure-Code>8</ACI-Disclosure-Code>
		<ACI-Disclosure-Text>Contracted by the owner to provide other (non-Energy Assessment) services.</ACI-Disclosure-Text>
	</ACI-Related-Party-Disclosure>
	<ACI-Related-Party-Disclosure>
		<ACI-Disclosure-Code>9</ACI-Disclosure-Code>
		<ACI-Disclosure-Text>Contracted by the owner to provide air conditioning maintenance services.</ACI-Disclosure-Text>
	</ACI-Related-Party-Disclosure>
		<Refrigerant-Type>
		<Type>HCFC 22</Type>
		<ECFGasRegulation>Not relevant</ECFGasRegulation>
		<ECOzoneRegulation>Relevant and must comply</ECOzoneRegulation>
	</Refrigerant-Type>
	<Refrigerant-Type>
		<Type>HCFC 123</Type>
		<ECFGasRegulation>Not relevant</ECFGasRegulation>
		<ECOzoneRegulation>Relevant and must comply</ECOzoneRegulation>
	</Refrigerant-Type>
	<Refrigerant-Type>
		<Type>HCFC 124</Type>
		<ECFGasRegulation>Not relevant</ECFGasRegulation>
		<ECOzoneRegulation>Relevant and must comply</ECOzoneRegulation>
	</Refrigerant-Type>
	<Refrigerant-Type>
		<Type>HCFC 142b</Type>
		<ECFGasRegulation>Not relevant</ECFGasRegulation>
		<ECOzoneRegulation>Relevant and must comply</ECOzoneRegulation>
	</Refrigerant-Type>
	<Refrigerant-Type>
		<Type>HFC 23</Type>
		<ECFGasRegulation>Relevant and must comply</ECFGasRegulation>
		<ECOzoneRegulation>Not relevant</ECOzoneRegulation>
	</Refrigerant-Type>
	<Refrigerant-Type>
		<Type>HFC 32</Type>
		<ECFGasRegulation>Relevant and must comply</ECFGasRegulation>
		<ECOzoneRegulation>Not relevant</ECOzoneRegulation>
	</Refrigerant-Type>
	<Refrigerant-Type>
		<Type>HFC 41</Type>
		<ECFGasRegulation>Relevant and must comply</ECFGasRegulation>
		<ECOzoneRegulation>Not relevant</ECOzoneRegulation>
	</Refrigerant-Type>
	<Refrigerant-Type>
		<Type>HFC 43-10mee</Type>
		<ECFGasRegulation>Relevant and must comply</ECFGasRegulation>
		<ECOzoneRegulation>Not relevant</ECOzoneRegulation>
	</Refrigerant-Type>
	<Refrigerant-Type>
		<Type>HFC 125</Type>
		<ECFGasRegulation>Relevant and must comply</ECFGasRegulation>
		<ECOzoneRegulation>Not relevant</ECOzoneRegulation>
	</Refrigerant-Type>
	<Refrigerant-Type>
		<Type>HFC 134</Type>
		<ECFGasRegulation>Relevant and must comply</ECFGasRegulation>
		<ECOzoneRegulation>Not relevant</ECOzoneRegulation>
	</Refrigerant-Type>
	<Refrigerant-Type>
		<Type>HFC 134a</Type>
		<ECFGasRegulation>Relevant and must comply</ECFGasRegulation>
		<ECOzoneRegulation>Not relevant</ECOzoneRegulation>
	</Refrigerant-Type>
	<Refrigerant-Type>
		<Type>HFC 143</Type>
		<ECFGasRegulation>Relevant and must comply</ECFGasRegulation>
		<ECOzoneRegulation>Not relevant</ECOzoneRegulation>
	</Refrigerant-Type>
	<Refrigerant-Type>
		<Type>HFC 143a</Type>
		<ECFGasRegulation>Relevant and must comply</ECFGasRegulation>
		<ECOzoneRegulation>Not relevant</ECOzoneRegulation>
	</Refrigerant-Type>
	<Refrigerant-Type>
		<Type>HFC 152a</Type>
		<ECFGasRegulation>Relevant and must comply</ECFGasRegulation>
		<ECOzoneRegulation>Not relevant</ECOzoneRegulation>
	</Refrigerant-Type>
	<Refrigerant-Type>
		<Type>HFC 227ea</Type>
		<ECFGasRegulation>Relevant and must comply</ECFGasRegulation>
		<ECOzoneRegulation>Not relevant</ECOzoneRegulation>
	</Refrigerant-Type>
	<Refrigerant-Type>
		<Type>HFC 236cb</Type>
		<ECFGasRegulation>Relevant and must comply</ECFGasRegulation>
		<ECOzoneRegulation>Not relevant</ECOzoneRegulation>
	</Refrigerant-Type>
	<Refrigerant-Type>
		<Type>HFC 236ea</Type>
		<ECFGasRegulation>Relevant and must comply</ECFGasRegulation>
		<ECOzoneRegulation>Not relevant</ECOzoneRegulation>
	</Refrigerant-Type>
	<Refrigerant-Type>
		<Type>HFC 236fa</Type>
		<ECFGasRegulation>Relevant and must comply</ECFGasRegulation>
		<ECOzoneRegulation>Not relevant</ECOzoneRegulation>
	</Refrigerant-Type>
	<Refrigerant-Type>
		<Type>HFC 245ca</Type>
		<ECFGasRegulation>Relevant and must comply</ECFGasRegulation>
		<ECOzoneRegulation>Not relevant</ECOzoneRegulation>
	</Refrigerant-Type>
